=== swapnild2111/carrom/data/statecircuit-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "StateCircuitSlams",
  "type": "object",
  "required": ["year", "lastUpdated", "summary", "tournaments", "districts", "players"],
  "properties": {
    "year": { "type": "integer" },
    "lastUpdated": { "type": "string", "format": "date" },
    "summary": { "type": "object" },
    "tournaments": { "type": "array" },
    "districts": { "type": "array" },
    "players": { "type": "array" }
  }
}

=== swapnild2111/carrom/static/data/statecircuit.json
{"year": 2025, "lastUpdated": "2026-06-28", "summary": {"players": 73, "tournaments": 10, "totals": {"white": 102, "black": 39, "all": 141}}, "tournaments": [{"id": "5th-rotary-club-of-mumbai-parleshwar", "name": "5th Rotary Club of Mumbai Parleshwar", "totals": {"white": 22, "black": 12, "all": 34}, "topPlayers": [{"name": "Mohd. Ghufran", "white": 2, "black": 2, "total": 4}, {"name": "Nilansh Hiten Chiplunkar", "white": 2, "black": 1, "total": 3}, {"name": "Pankaj Ashok Pawar", "white": 2, "black": 1, "total": 3}]}, {"id": "2nd-ghatkopar-jolly-gymkhana", "name": "2nd Ghatkopar Jolly Gymkhana", "totals": {"white": 23, "black": 4, "all": 27}, "topPlayers": [{"name": "Mohd. Ghufran", "white": 3, "black": 0, "total": 3}, {"name": "Prashant Suryakant More", "white": 3, "black": 0, "total": 3}, {"name": "Siddhant Mahendra Wadwalkar", "white": 2, "black": 1, "total": 3}]}, {"id": "kshatriya-union-club-vanmali-hall-ac", "name": "Kshatriya Union Club - Vanmali Hall AC", "totals": {"white": 17, "black": 4, "all": 21}, "topPlayers": [{"name": "Sandip Ashok Dive", "white": 2, "black": 0, "total": 2}, {"name": "Dilip Sosa", "white": 1, "black": 0, "total": 1}, {"name": "Fahim Yakub Kazi", "white": 1, "black": 0, "total": 1}]}, {"id": "16th-shivaji-park-gymkhana", "name": "16th SHIVAJI PARK GYMKHANA", "totals": {"white": 13, "black": 4, "all": 17}, "topPlayers": [{"name": "Jitesh Ashok Kadam", "white": 3, "black": 0, "total": 3}, {"name": "Bhavesh Kishor Parmar", "white": 1, "black": 0, "total": 1}, {"name": "Mitali Bhavesh Pathak", "white": 1, "black": 0, "total": 1}]}, {"id": "9th-mandpeshwar-civic-federation", "name": "9th Mandpeshwar Civic Federation", "totals": {"white": 7, "black": 6, "all": 13}, "topPlayers": [{"name": "Jitesh Ashok Kadam", "white": 2, "black": 0, "total": 2}, {"name": "Prashant Suryakant More", "white": 1, "black": 1, "total": 2}, {"name": "Pankaj Ashok Pawar", "white": 1, "black": 0, "total": 1}]}, {"id": "3rd-the-chembur-gymkhana", "name": "3rd The Chembur Gymkhana", "totals": {"white": 8, "black": 1, "all": 9}, "topPlayers": [{"name": "Sandip Ashok Dive", "white": 2, "black": 0, "total": 2}, {"name": "Amol Ashok Sawardekar", "white": 1, "black": 0, "total": 1}, {"name": "Jitesh Ashok Kadam", "white": 1, "black": 0, "total": 1}]}, {"id": "58th-senior-maharashtra-state-carrom-championship", "name": "58th Senior Maharashtra State Carrom Championship", "totals": {"white": 3, "black": 4, "all": 7}, "topPlayers": [{"name": "Prashant Suryakant More", "white": 2, "black": 0, "total": 2}, {"name": "Pankaj Ashok Pawar", "white": 1, "black": 0, "total": 1}, {"name": "Anil Dilip Mundhe", "white": 0, "black": 1, "total": 1}]}, {"id": "3rd-guardian-minister-chashak-sindhudurg", "name": "3rd Guardian Minister Chashak Sindhudurg", "totals": {"white": 6, "black": 0, "all": 6}, "topPlayers": [{"name": "Vikas Harish Dharia", "white": 2, "black": 0, "total": 2}, {"name": "Sachin Nandu Bandal", "white": 1, "black": 0, "total": 1}, {"name": "Sandip Ashok Dive", "white": 1, "black": 0, "total": 1}]}, {"id": "late-vinayak-nimhan-ex-mla-pune", "name": "Late Vinayak Nimhan (Ex.MLA) Pune", "totals": {"white": 2, "black": 3, "all": 5}, "topPlayers": [{"name": "Mayur Gajanan Chavan", "white": 1, "black": 0, "total": 1}, {"name": "Vikas Harish Dharia", "white": 1, "black": 0, "total": 1}, {"name": "Abhijit Dattatray Tripankar", "white": 0, "black": 1, "total": 1}]}, {"id": "8th-shree-dattaraj-charitable-trust-nrusinghawadi", "name": "8th SHREE DATTARAJ CHARITABLE TRUST, NRUSINGHAWADI", "totals": {"white": 1, "black": 1, "all": 2}, "topPlayers": [{"name": "Omkar Prasanna Tilak", "white": 1, "black": 0, "total": 1}, {"name": "Prashant Suryakant More", "white": 0, "black": 1, "total": 1}]}], "districts": [{"name": "Mumbai", "players": 40, "totals": {"white": 63, "black": 18, "all": 81}}, {"name": "Mumbai Sub", "players": 11, "totals": {"white": 20, "black": 5, "all": 25}}, {"name": "Pune", "players": 13, "totals": {"white": 9, "black": 11, "all": 20}}, {"name": "Thane", "players": 6, "totals": {"white": 9, "black": 3, "all": 12}}, {"name": "Palghar", "players": 2, "totals": {"white": 1, "black": 1, "all": 2}}, {"name": "Ratnagiri", "players": 1, "totals": {"white": 0, "black": 1, "all": 1}}], "players": [{"id": "prashant-suryakant-more", "name": "Prashant Suryakant More", "gender": "male", "district": "Mumbai", "displayOrder": 1, "totals": {"white": 9, "black": 3, "all": 12}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 1}, "2nd-ghatkopar-jolly-gymkhana": {"white": 3, "black": 0}, "58th-senior-maharashtra-state-carrom-championship": {"white": 2, "black": 0}, "9th-mandpeshwar-civic-federation": {"white": 1, "black": 1}, "kshatriya-union-club-vanmali-hall-ac": {"white": 1, "black": 0}, "8th-shree-dattaraj-charitable-trust-nrusinghawadi": {"white": 0, "black": 1}}}, {"id": "sandip-ashok-dive", "name": "Sandip Ashok Dive", "gender": "male", "district": "Mumbai Sub", "displayOrder": 2, "totals": {"white": 8, "black": 1, "all": 9}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 0}, "16th-shivaji-park-gymkhana": {"white": 1, "black": 0}, "3rd-guardian-minister-chashak-sindhudurg": {"white": 1, "black": 0}, "3rd-the-chembur-gymkhana": {"white": 2, "black": 0}, "kshatriya-union-club-vanmali-hall-ac": {"white": 2, "black": 0}, "9th-mandpeshwar-civic-federation": {"white": 0, "black": 1}}}, {"id": "mohd-ghufran", "name": "Mohd. Ghufran", "gender": "male", "district": "Mumbai", "displayOrder": 3, "totals": {"white": 5, "black": 4, "all": 9}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 2}, "2nd-ghatkopar-jolly-gymkhana": {"white": 3, "black": 0}, "16th-shivaji-park-gymkhana": {"white": 0, "black": 1}, "9th-mandpeshwar-civic-federation": {"white": 0, "black": 1}}}, {"id": "jitesh-ashok-kadam", "name": "Jitesh Ashok Kadam", "gender": "male", "district": "Mumbai Sub", "displayOrder": 4, "totals": {"white": 6, "black": 0, "all": 6}, "byTournament": {"16th-shivaji-park-gymkhana": {"white": 3, "black": 0}, "3rd-the-chembur-gymkhana": {"white": 1, "black": 0}, "9th-mandpeshwar-civic-federation": {"white": 2, "black": 0}}}, {"id": "vikas-harish-dharia", "name": "Vikas Harish Dharia", "gender": "male", "district": "Mumbai", "displayOrder": 5, "totals": {"white": 6, "black": 0, "all": 6}, "byTournament": {"16th-shivaji-park-gymkhana": {"white": 1, "black": 0}, "3rd-guardian-minister-chashak-sindhudurg": {"white": 2, "black": 0}, "late-vinayak-nimhan-ex-mla-pune": {"white": 1, "black": 0}, "9th-mandpeshwar-civic-federation": {"white": 1, "black": 0}, "kshatriya-union-club-vanmali-hall-ac": {"white": 1, "black": 0}}}, {"id": "pankaj-ashok-pawar", "name": "Pankaj Ashok Pawar", "gender": "male", "district": "Thane", "displayOrder": 6, "totals": {"white": 5, "black": 1, "all": 6}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 1}, "2nd-ghatkopar-jolly-gymkhana": {"white": 1, "black": 0}, "58th-senior-maharashtra-state-carrom-championship": {"white": 1, "black": 0}, "9th-mandpeshwar-civic-federation": {"white": 1, "black": 0}}}, {"id": "siddhant-mahendra-wadwalkar", "name": "Siddhant Mahendra Wadwalkar", "gender": "male", "district": "Mumbai", "displayOrder": 7, "totals": {"white": 2, "black": 3, "all": 5}, "byTournament": {"2nd-ghatkopar-jolly-gymkhana": {"white": 2, "black": 1}, "5th-rotary-club-of-mumbai-parleshwar": {"white": 0, "black": 1}, "58th-senior-maharashtra-state-carrom-championship": {"white": 0, "black": 1}}}, {"id": "abhijit-dattatray-tripankar", "name": "Abhijit Dattatray Tripankar", "gender": "male", "district": "Pune", "displayOrder": 8, "totals": {"white": 1, "black": 3, "all": 4}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 1, "black": 2}, "late-vinayak-nimhan-ex-mla-pune": {"white": 0, "black": 1}}}, {"id": "hareshwar-gangaprasad-betvanshi", "name": "Hareshwar Gangaprasad Betvanshi", "gender": "male", "district": "Mumbai", "displayOrder": 9, "totals": {"white": 3, "black": 0, "all": 3}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 0}, "kshatriya-union-club-vanmali-hall-ac": {"white": 1, "black": 0}}}, {"id": "prafull-suryakant-more", "name": "Prafull Suryakant More", "gender": "male", "district": "Mumbai", "displayOrder": 10, "totals": {"white": 3, "black": 0, "all": 3}, "byTournament": {"2nd-ghatkopar-jolly-gymkhana": {"white": 2, "black": 0}, "kshatriya-union-club-vanmali-hall-ac": {"white": 1, "black": 0}}}, {"id": "nilansh-hiten-chiplunkar", "name": "Nilansh Hiten Chiplunkar", "gender": "male", "district": "Mumbai", "displayOrder": 11, "totals": {"white": 2, "black": 1, "all": 3}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 2, "black": 1}}}, {"id": "sanjay-baliram-mande", "name": "Sanjay Baliram Mande", "gender": "male", "district": "Mumbai", "displayOrder": 12, "totals": {"white": 2, "black": 1, "all": 3}, "byTournament": {"5th-rotary-club-of-mumbai-parleshwar": {"white": 1, "black": 1}, "16th-shivaji-park-gymkhana": {"white": 1, "black": 0}}}, {"id": "saurabh-shreekrishna-mate", "name": "Saurabh Shreekrishna Mate", "gender": "male", "district": "Mumbai", "displayOrder": 13, "totals": {"white": 2, "black": 1, "all": 3}, "byTournament": {"2nd-ghatkopar-jolly-gymkhana": {"white": 2, "black": 0}, "5th-rotary-club-of-mumbai-parleshwar": {"white": 0, "black": 1}}}, {"id": "yogesh-udaybhan-pardeshi", "name": "Yogesh Udaybhan Pardeshi", "gender": "male", "district": "Pune", "displayOrder": 14, "totals": {"white": 1, "black": 2, "all": 3}, "byTournament": {"3rd-guardian-minister-chashak-sindhudurg": {"white": 1, "black": 0}, "58th-senior-maharashtra-state-carrom-championship": {"white": 0, "black": 1}, "kshatriya-union-club-vanmali-hall-ac": {"white": 0, "black": 1}}}, {"id": "omkar-prasanna-tilak", "name": "Omkar Prasanna Tilak", "gender": "male", "district": "Mumbai", "displayOrder": 15, "totals": {"white": 2, "black": 0, "a
